### PR TITLE
Sync with std/json

### PR DESCRIPTION
**Pull request by planetis-m**
Fix some issues encountered when trying to port from std/json.

1. export `JsonParserError`, as it is needed for catching exception when `parseJson`
1. `` `%`(x: ref object)`` fails to compile (Got `JsonNode` but expected `JsonTree`)
1. port [commit](https://github.com/nim-lang/Nim/commit/a0cb1a80dd61428de8046cee25e664b41156e6ab) (`%*` macro)
1. Removed unused import `unicode`
1. Ported `to` macro and added tests from stdlib.

### CODE REVIEW

**Comment by planetis-m** [comment]
Also what about other `%` overloads? `json.nim` also contains procs:

```nim
proc `%`*[T](table: Table[string, T]|OrderedTable[string, T]): JsonNode
proc `%`*[T](opt: Option[T]): JsonNode
```
Is it ok if it imports `tables` and `options`? Do they return `JsonNode` or rather `JsonTree`?

**Comment by planetis-m** [comment]
@Araq please review

**Comment by planetis-m** [comment]
I avoided importing table and options, let me know if I can add them.

**Comment by Araq** [comment]
It's great but since we departure from the API already quite a bit, can we have the serializer code in a different module?

**Comment by planetis-m** [comment]
Thank you!

**Pull request merged**
